spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/goodjob?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ENC(7JY14CMZTTa1RORczVt2Hw==)
    password: ENC(dSo9G4/D9uroek5yMfBnKw/+w16gkSpf)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
