server:
  port: 8080

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: message/messages
    encoding: UTF-8


